### ISSUE TITLE
error while external module export to window var with special key  

### ISSUE THREAD

**Issue by caijiehong** [crcong/vite-plugin-externals#1]
I have a external module `@namespace/something`, and export to window var with the key `@namespace/something`

so I set the plugin config like this
```js
viteExternalsPlugin({'@namespace/something' : '@namespace/something'})
```

and the using code like this
```js
import { foo } from '@namespace/something'
```

then the code generated by the plugin go error like this

```js
const foo = window.@namespace/something.foo
```

while it should be like this
```js
const foo = window['@namespace/something'].foo
```

**Comment by crcong** [comment]
Thank you for your feedback. I'm not considerate. I'll fix it now.

**Comment by caijiehong** [comment]
> Thank you for your feedback. I'm not considerate. I'll fix it now.

I have try fix it, and create a pr for u. please check.

**Comment by crcong** [comment]
> I have try fix it, and create a pr for u. please check.
Thanks~
