### ISSUE TITLE
build完成后sourcemap失效

### ISSUE THREAD

**Issue by CYYSILVER** [crcong/vite-plugin-externals#10]
![image](https://user-images.githubusercontent.com/48582184/145928797-255e10c5-483c-403a-b945-00c71476b1e4.png)

1. 设置 build.sourcemap 为 true
2. 进行 build
3. build 完成后，非 node_modules 下的文件sourcemap失效

查了下文档，如果需要提供sourcemap，则需要返回 `map: null`（未对原代码进行修改）或者返回新的 `map: newMap`
https://github.com/crcong/vite-plugin-externals/blob/62bb6256ec37134e47e3fab94c588ff68f4bc17a/src/index.ts#L127
改成这样就能修复
```js
return { code, map: null }
```

**Comment by crcong** [comment]
fixed in #11
