### ISSUE TITLE
0.3.3 version  regular expresion cause error

### ISSUE THREAD

**Issue by IBICF** [crcong/vite-plugin-externals#14]
![image](https://user-images.githubusercontent.com/14859651/151514322-58a843dd-aacf-4b32-a518-e249c27cf5a3.png)

when i update version from 0.3.2 to 0.3.3, i got error below

![image](https://user-images.githubusercontent.com/14859651/151514669-f9125c64-bf49-44b5-937d-66f4ee146551.png)

when i change  /\.(mjs|js|ts|vue|jsx|tsx)(\?.*|)$/ to /\.(mjs|js|ts|vue|jsx|tsx)$/

it will perform well

**Comment by crcong** [comment]
你好，我这边简单测试了一下，没重现这个报错，可以提供下可复现报错的仓库吗？谢谢~

**Comment by sha123hul** [comment]
I have the same issue in vue single page template in <style> tag. changing /.(mjs|js|ts|vue|jsx|tsx)(?.*|)$/ to /.(mjs|js|ts|vue|jsx|tsx)$/ fixed the issue for me too
