### ISSUE TITLE
Provide A Way to Config Source Map Creation To Avoid Building Crash Caused By Hi-Res Sourcemap

### ISSUE THREAD

**Issue by lo-tp** [crcong/vite-plugin-externals#15]
The current config about source mapping is to create the most accurate source map which can under certain circumstances cause  building failure like the following image.
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/6308071/153328944-09078d12-1877-4f8c-a0a8-42a0b8ca054c.png">
The root cause is this [line](https://github.com/crcong/vite-plugin-externals/blob/main/src/index.ts#L142). By turning of hi-res this problem can be solved.
I was wondering if it is viable to provide an option to control the config of source-map generation: Like the following git diff shows
![image](https://user-images.githubusercontent.com/6308071/153329462-aadaa62c-82e6-4ca1-b4b9-889b75b19241.png)

**Comment by crcong** [comment]
Thank you for your feedback. You can solve this problem by `sourceMapOptions` option. Such as `{ sourceMapOptions: { hires: false } }`
