### ISSUE TITLE
添加filter 配置之后window.Vue 转换失败

### ISSUE THREAD

**Issue by yqwang0802** [crcong/vite-plugin-externals#18]
如下配置，打包后搜索代码。发现没有window.Vue。删掉filter后打包，就有window.Vue
 plugins: [
      vue(),
      viteExternalsPlugin(
        {
          vue: 'Vue',
          'vue-router': 'VueRouter',
          // axios: 'axios',
          
        }, {
          filter(code, id) {
            // console.log(id, 'pinia pinia ');
            // 处理 pinia，解决 cdn 加载 Vue 响应式丢失问题
            if (id.includes('pinia')) {
              // console.log(id, 'pinia pinia ');
              return true;
            }
            return false;
          },
          disableInServe: true,
        }
       
      ),
    ],

**Comment by crcong** [comment]
你好，配置 filter 函数，返回 `true` 才会转换哦，你这样写是 id 中函数 pinia，才会被转换，其他模块不会被转换。

我觉得你的意思是

```js
filter(code, id) {
  if (id.includes('pinia')) {
    return false; // 这里是不是写反了
  }
  return true; // 这里是不是写反了
}
```
