### ISSUE TITLE
在和自动导入插件同时使用时的问题优化

### ISSUE THREAD

**Issue by nineszsoo** [crcong/vite-plugin-externals#21]
#### 下面是我查看的使用自动导入 `ref` 时插件的执行顺序。
![image](https://user-images.githubusercontent.com/76999714/189127835-d8957aee-09c7-43d9-90b4-8fe838cee50c.png)
#### 然后我在 `node_modules` 下面修改了 `vite-plugin-externals` 的 `index.js` 中关于该插件的返回对象（添加了属性`enforce: 'post'`）后就可以正常使用了。
![image](https://user-images.githubusercontent.com/76999714/189129197-60647acd-5553-471b-bba2-1fa1bfaaed52.png)

**Comment by Clareyang213** [comment]
我按这种方式修改之后，打包后，unplugin-auto-import 自动导入还是有问题，还有没有其他解决方案

**Comment by Clareyang213** [comment]
解决了，vite打包的时候，自动导入应该使用'unplugin-auto-import/rollup'

`import AutoImportVite from 'unplugin-auto-import/vite';
import AutoImportRollup from 'unplugin-auto-import/rollup';

// cdn链接
const cdn = {
    vue: 'Vue',
    // 👇 配置 vue-demi 全局变量 👇
    'vue-demi': 'VueDemi',
    pinia: 'Pinia',
    'vue-router': 'VueRouter'
}；
export default defineConfig(({ command }) => {
    return {
        plugins: [
            vue(),
            viteExternalsPlugin(cdn.externals),
            command !== 'build' &&
                AutoImportVite({
                    // 后续vue/vue-router/pinia的API都不需要再单独import到setup里面了
                    imports: ['vue', 'vue-router', 'pinia']
                })
        ],
        build: {
            rollupOptions: {
                plugins: [AutoImportRollup({ imports: ['vue', 'vue-router', 'pinia'] })]
            }
        }
    }；
});`

**Comment by cq-cute** [comment]
> 解决了，vite打包的时候，自动导入应该使用'unplugin-auto-import/rollup'
> 
> `import AutoImportVite from 'unplugin-auto-import/vite'; import AutoImportRollup from 'unplugin-auto-import/rollup';
> 
> // cdn链接 const cdn = { vue: 'Vue', // 👇 配置 vue-demi 全局变量 👇 'vue-demi': 'VueDemi', pinia: 'Pinia', 'vue-router': 'VueRouter' }； export default defineConfig(({ command }) => { return { plugins: [ vue(), viteExternalsPlugin(cdn.externals), command !== 'build' && AutoImportVite({ // 后续vue/vue-router/pinia的API都不需要再单独import到setup里面了 imports: ['vue', 'vue-router', 'pinia'] }) ], build: { rollupOptions: { plugins: [AutoImportRollup({ imports: ['vue', 'vue-router', 'pinia'] })] } } }； });`

这样配置之后打包的时候还是没有自动引入，你用的哪个版本啊
