### ISSUE TITLE
Vue example doesn't work

### ISSUE THREAD

**Issue by geoffSwenson** [crcong/vite-plugin-externals#23]
If you run npm install for the vite-plugin-externals\examples\vue example
it gives an error:
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

How do I fix this?

**Comment by crcong** [comment]
This project's package manager is [pnpm](https://github.com/pnpm/pnpm). You can execute `pnpm i` in project root directory to install dependecies.

About `"workspace:": workspace:*`, you can get more information from monorepo.
