### ISSUE TITLE
优化：可否像webpack external那样处理(✺ω✺)

### ISSUE THREAD

**Issue by Xli33** [crcong/vite-plugin-externals#31]
一个关于pinia偏要适配还走vue-demi适配vue2导致的坑已经有人提了 #19 ，就不赘述了嘻嘻|･ω･)

关于处理后的代码，不配置 useWIndow: false 的话都替换成了 window[module] 就赶脚有点占字数Σ(⊙▽⊙，配置了 useWindow: true 的话不能用全局变量名引入，比如 `import axios from 'axios'` ，否则会报错 `cannot access 'axios' before initialization` ，因为变成了 `const axios = axios`     o(╥﹏╥)o
P.S 找了各种vite的external相关插件，要么不适配vite 4，要么只在build生效，有2个像webpack那样处理的也坑死，vite-plugin-external 受rollup的zz限制只能改输出文件格式才行，另一个也有了不起的 [bug](https://github.com/yellowspot/vite-plugin-externals/issues/1) 

ε=(´ο｀*)))唉 3202了入vite还是心好累，各种坑，又不是本地跑个demo就完事儿(ಥ﹏ಥ)、、、、

**Comment by crcong** [comment]
如果需要像 webpack external 处理的话，需要侵入 vite 和 rollup 的模块解析系统，这就复杂很多了 :(

当时公司的项目 webpack 转 vite，也是遇到这个这个 external 怎么配置都不生效，权宜之计才写了这个插件，确实是解决了当时的问题。但后来发现转换代码并不能覆盖模块化的所有语法，例如 #19 

最近没在搞 vite 了，公司的项目也跑得好好的。希望 vite 能尽早支持这个功能吧，或者这是受限于 rollup ？

**Comment by Xli33** [comment]
> 如果需要像 webpack external 处理的话，需要侵入 vite 和 rollup 的模块解析系统，这就复杂很多了 :(
> 
> 当时公司的项目 webpack 转 vite，也是遇到这个这个 external 怎么配置都不生效，权宜之计才写了这个插件，确实是解决了当时的问题。但后来发现转换代码并不能覆盖模块化的所有语法，例如 #19
> 
> 最近没在搞 vite 了，公司的项目也跑得好好的。希望 vite 能尽早支持这个功能吧，或者这是受限于 rollup ？

好的，谢谢，那我先关了♪(･ω･)ﾉ

**Comment by nonzzz** [comment]
@Xli33 可以尝试下[vite-plugin-cdn2](https://github.com/nonzzz/vite-plugin-cdn)
