### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED')

### ISSUE THREAD

**Issue by baskaal** [crcong/vite-plugin-externals#37]
I've been struggling with externals related errors while trying to import a react module I'm building with Vite. With the normal rollup externals config I kept getting `Cannot read properties of null (reading 'useEffect')`, so React itself being null, and with different config I got `window is undefined`. With this plugin these errors seem to be solved. At the moment I'm still getting this error:

```
TypeError: Cannot read properties of undefined (reading '__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED')
```

It seems weird because it's also a property of the React object, which is accessable now. I can't find anything helpful about it so figured asking here. Somebody knows what I'm doing wrong?

Bit more context: I listed these packages as `devDependencies` and `peerDependencies` and they are installed in the other project, the other project is in Next, I don't think thats related to the issue though.

This is the config I'm passing:

```
    external({
      react: 'React',
      'react-dom': 'ReactDOM',
      'styled-components': 'styled'
    }, {
      useWindow: false,
      disableSsr: true
    })
```

**Comment by baskaal** [comment]
Closing because I found a workaround and this issue didn't seem to be caused by this package.

**Comment by ncls-alien** [comment]
Would be nice to share the workaround though...
