### ISSUE TITLE
HMR fails when I use this plugin!!

### ISSUE THREAD

**Issue by lileilei** [crcong/vite-plugin-externals#5]
vite.config.js  config
```
export default defineConfig({
  plugins: [
    viteExternalsPlugin({
      react: 'React',
      'react-dom': 'ReactDOM',
    }),
    reactRefresh()
]})
```

**Comment by crcong** [comment]
Thank you for your feedback.

But I can't reproduce it with this config. Can you provide more information or a mini repository?

**Comment by lileilei** [comment]
Repository Url ： https://github.com/lileilei/vite-react

My plugin vite-plugin-react-federation can't find the vite virtual vite:react address, so I use the vite-plugin-externals to fix this problem. I have cleaned up the relevant code, used the initializer code of Vite React Templete, and used your plugin

**Comment by lileilei** [comment]
广州的兄弟，你好！现在除了HMR 模块联邦一切都正常了现在，rollup插件这块我还不是很熟悉，改造的别人的插件，如果有兴趣帮忙改造优化下? 我觉得使用vite的开发体验，加上模块联邦工程化可以解决很多问题! 据我了解，目前模块联邦还没有vite的相关项目

**Comment by crcong** [comment]
可以呀~ 晚点我详细看下你的项目，现在在上班搬砖呢~ 方便的话，可以发下你的微信，或者我等下加你qq

**Comment by crcong** [comment]
Because the `react` loaded in the HTML file is `production` mode (.min.js). Hasn't `__REACT_DEVTOOLS_GLOBAL_HOOK__` object, cause HMR fails.

Solution: loaded `development` mode library in html.

Vue has the same problem.

I consider that  provide some options, such as not to transofrm external in the dev mode...

**Comment by wqcstrong** [comment]
老哥这个有好的解决方案了么？如果不想用 `development` 的话，也不想在 html 中模板替换，就想用你这个插件一把梭。

**Comment by wqcstrong** [comment]
其实 external 的功能只需要在 `build` mode 使用，所以做一下改动应该就行的吧？
1. https://github.com/crcong/vite-plugin-externals/blob/a6c45417c9225dc0c4c70cea291cb5655f2d46f9/src/index.ts#L45-L47 改成
```js
if (mode === 'development') {
  return;
}
```

2. 在 `transform` 入口处新增判断， https://github.com/crcong/vite-plugin-externals/blob/a6c45417c9225dc0c4c70cea291cb5655f2d46f9/src/index.ts#L81
```js
if (!isBuild) {
  return;
}
```
